version: "3.8"

services:
  svelte:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
